# -*- coding: utf-8 -*-
"""European Market Stock Simulation & Risk Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HscLWvJ1WhwPQ5J5Plo_p2ZpB_iO1StL
"""

import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf


ticker = yf.Ticker("^STOXX50E")
latest = ticker.history(period="1d")


latest_close = latest['Close'].iloc[-1]


S0 = latest_close
prices = yf.download("^NSEI", period="5y")['Close']
log_returns = np.log(prices / prices.shift(1)).dropna()

mu = log_returns.mean() * 252
sigma = log_returns.std() * np.sqrt(252)

T = 1
N = 252
dt = T / N

Z = np.random.normal(0, 1, N)

S = np.zeros(N)
S[0] = S0
for t in range(1, N):
    S[t] = S[t-1] * np.exp((mu - 0.5 * sigma**2)*dt + sigma*np.sqrt(dt)*Z[t])

plt.plot(S, c="red", alpha=1)
plt.title("Stock pricing uisng GBM")
plt.xlabel("Day")
plt.ylabel("Price(€)")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

ticker = yf.Ticker("^STOXX50E")
latest = ticker.history(period="1d")
latest_close = latest['Close'].iloc[-1]


S0 = latest_close
mu = 0.10
sigma = 0.1123
T = 1
N = 252
dt = T / N
M = 10000


price_paths = np.zeros((M, N+1))
price_paths[:, 0] = S0


Z = np.random.normal(0, 1, size=(M, N))


for t in range(1, N+1):
    price_paths[:, t] = price_paths[:, t-1] * np.exp(
        (mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * Z[:, t-1]
    )

final_prices = price_paths[:, -1]


fig, axs = plt.subplots(1, 2, figsize=(16, 6))


for i in range(10000):
    axs[0].plot(price_paths[i],)
axs[0].set_title("price paths using monte carlo model")
axs[0].set_xlabel("no. of days traded")
axs[0].set_ylabel("Price")
axs[0].legend()
axs[0].grid(True)

axs[1].hist(final_prices, bins=100, edgecolor='green')
axs[1].set_title("Final simulated prices for 1 year")
axs[1].set_xlabel("latest price")
axs[1].set_ylabel("Occurence")
axs[1].grid(True)

mean_price = np.mean(final_prices)
var_5 = np.percentile(final_prices, 5)
prob_loss = np.mean(final_prices < S0)


risk_text = (
    f"Mean Final Price: €{mean_price:.2f}\n"
    f"5% VaR: €{var_5:.2f} (loss: {S0-var_5:.2f})\n"
    f"Probability of Loss: {prob_loss:.2%}"
)


plt.gca().text(
    0.95, 0.95, risk_text,
    transform=plt.gca().transAxes,
    fontsize=12,
    verticalalignment='top',
    horizontalalignment='right',
    bbox=dict(boxstyle="round,pad=0.4", facecolor='white', edgecolor='gray')
)


plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf


n_assets = 3

tickers = ["ASML.AS", "SAP.DE", "MC.PA"]

def stock_pricing(symbol):
    ticker = yf.Ticker(symbol)
    latest = ticker.history(period="1d")
    return latest['Close'].iloc[-1]


S0 = np.array([stock_pricing(t) for t in tickers])


T = 1
N = 252
dt = T / N


weights = np.array([0.4, 0.3, 0.3])


mu = np.array([0.08, 0.12, 0.10])
sigma = np.array([0.15, 0.20, 0.18])


corr_matrix = np.array([
    [1.0, 0.2, 0.4],
    [0.2, 1.0, 0.3],
    [0.4, 0.3, 1.0]
])

cov_matrix = np.outer(sigma, sigma) * corr_matrix
L = np.linalg.cholesky(cov_matrix)

M = 10000


price_paths = np.zeros((M, N + 1, n_assets))
price_paths[:, 0, :] = S0


for m in range(M):
    Z = np.random.normal(size=(N, n_assets))
    correlated_Z = Z @ L.T
    for t in range(1, N + 1):
        price_paths[m, t, :] = price_paths[m, t - 1, :] * np.exp(
            (mu - 0.5 * sigma**2) * dt + np.sqrt(dt) * correlated_Z[t - 1]
        )

portfolio_values = np.sum(price_paths * weights, axis=2)


initial_portfolio_value = np.sum(S0 * weights)
scale_factor = 100000 / initial_portfolio_value
portfolio_values *= scale_factor


fig, axs = plt.subplots(1, 2, figsize=(16, 6))

for i in range(10000):
    axs[0].plot(portfolio_values[i])
axs[0].set_title("Sample simulated paths of the portfolio")
axs[0].set_xlabel("Time in days")
axs[0].set_ylabel("total Value (€)")
axs[0].grid(True)


weights_percent = weights * 100
textstr = '\n'.join((
    "Starting Prices:",
    *(f"{tickers[i]}: {weights_percent[i]:.1f}% @ €{S0[i]:.2f}" for i in range(n_assets))
))
props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
axs[0].text(0.05, 0.95, textstr, transform=axs[0].transAxes, fontsize=10,
            verticalalignment='top', bbox=props)


final_values = portfolio_values[:, -1]
axs[1].hist(final_values, bins=50, edgecolor='black')
axs[1].set_title("final portfolio value distribution")
axs[1].set_xlabel("totla value at T(€)")
axs[1].set_ylabel("Occurence")
axs[1].grid(True)


VaR_95 = np.percentile(final_values, 5)


axs[1].axvline(VaR_95, color='r', linestyle='--', label=f'VaR (5%): €{VaR_95:,.0f}')


pct_loss = np.mean(final_values < 100000) * 100
axs[1].axvline(100000, color='orange', linestyle='--', label='initial value of portfolio')
axs[1].legend()


textstr2 = f"Risk value at 5th quantile: €{VaR_95:,.2f}\n" \
           f"P(loss) (below €100k): {pct_loss:.2f}%"

axs[1].text(0.95, 0.95, textstr2, transform=axs[1].transAxes, fontsize=10,
            verticalalignment='top', horizontalalignment='right',
            bbox=props)


plt.tight_layout()
plt.show()